# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-07-18 17:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('author', models.CharField(blank=True, max_length=20)),
                ('content', models.TextField()),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('isdelete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'article',
                'ordering': ['id'],
            },
            managers=[
                ('articleman', django.db.models.manager.Manager()),
            ],
        ),
    ]
