# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-07-22 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='isdelete',
            field=models.BooleanField(default=False),
        ),
    ]
