# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-07-25 05:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_auto_20200723_0911'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['uploadtime']},
        ),
        migrations.AddField(
            model_name='comments',
            name='root',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='root_comment', to='comments.Comments'),
        ),
    ]
