# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-07-25 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_auto_20200725_0557'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='cappreciatenum',
            field=models.IntegerField(default=0),
        ),
    ]
