# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-07-25 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0006_comments_cappreciateuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='cappreciateuser',
            field=models.TextField(null=True),
        ),
    ]
