# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-07-25 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0007_auto_20200725_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='cappreciateuser',
            field=models.TextField(default='{"user":[]}'),
        ),
    ]
