# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-07-21 12:19
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='blog',
            managers=[
                ('blogmanager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='blogtype',
            managers=[
                ('typemanager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
