# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-07-21 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200721_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='readnum',
            field=models.IntegerField(default=0),
        ),
    ]
