# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-07-25 08:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_readnum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='readnum',
            new_name='bappreciatenum',
        ),
    ]
