# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-07-25 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200725_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='bappreciateuser',
            field=models.TextField(null=True),
        ),
    ]
