# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-08-01 15:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200725_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blogtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blog.Blogtype'),
        ),
    ]
