# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-11-25 20:25
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('wenku', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='wenku',
            managers=[
                ('wkmanager', django.db.models.manager.Manager()),
            ],
        ),
    ]
